# Generated by Django 5.1.1 on 2024-10-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Questionsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supercategory', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('content_array', models.JSONField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
