# Generated by Django 4.2.16 on 2024-10-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0003_customuser_code_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
