# Generated by Django 5.1.1 on 2024-11-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0003_profile_delete_coderegister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rankdom',
        ),
        migrations.AddField(
            model_name='questionsset',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 15, 1, 14, 29577)),
        ),
        migrations.AddField(
            model_name='questionsset',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionsset',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionsset',
            name='title',
            field=models.CharField(default='Popular Soccer Players', max_length=150),
            preserve_default=False,
        ),
    ]
