# Generated by Django 4.2.16 on 2024-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
