# Generated by Django 5.1.1 on 2024-11-07 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0004_delete_rankdom_questionsset_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questionsset',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 16, 45, 23, 250704)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
