# Generated by Django 5.1.1 on 2024-11-14 14:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0005_customuser_image_alter_questionsset_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsset',
            name='emoji',
            field=models.CharField(default='⚽', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsset',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 15, 1, 22, 80034)),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankdom.customuser')),
            ],
        ),
    ]
