# Generated by Django 4.2.16 on 2024-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0006_alter_userregistration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
