# Generated by Django 4.2.16 on 2024-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0007_alter_userregistration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
