# Generated by Django 5.1.1 on 2024-11-14 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0007_questionsset_user_alter_questionsset_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsset',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 15, 18, 40, 465219)),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('supercategory', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 11, 14, 15, 18, 40, 466225))),
                ('content_array', models.JSONField(max_length=400)),
                ('emoji', models.CharField(max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rankdom.customuser')),
            ],
        ),
    ]
