# Generated by Django 4.2.16 on 2024-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0008_coderegister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
