# Generated by Django 4.2.16 on 2024-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0010_userdata_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
    ]
