# Generated by Django 4.2.16 on 2024-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdom', '0011_delete_userdata_remove_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderegister',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
